---
- name: Listen for events on dt_webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_webhook:
        host: 0.0.0.0
        port: 5000
        token: '123456789'

  rules:
    - name: Check nginx status
      condition: event.payload.eventData["data"] == "nginx"
      action:
        run_job_template:
          name: "Dynatrace nginx check job template"
          organization: "Default"  

    - name: Remediation
      condition: event.payload.eventData["data"] == "remediation"
      action:
        run_job_template:
          name: "Dynatrace remediation job template"
          organization: "Default"
